/* ============================================================================
 * File:   mod.rs
 * Author: Cole Johnson
 * ============================================================================
 * Copyright (c) 2020-2021 Cole Johnson
 *
 * This file is part of r86.
 *
 * r86 is free software: you can redistribute it and/or modify it under the
 *   terms of the GNU General Public License as published by the Free Software
 *   Foundation, either version 3 of the License, or (at your option) any later
 *   version.
 *
 * r86 is distributed in the hope that it will be useful, but WITHOUT ANY
 *   WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 *   FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 *   details.
 *
 * You should have received a copy of the GNU General Public License along with
 *   r86. If not, see <http://www.gnu.org/licenses/>.
 * ============================================================================
 */
mod p2intersect;
mod pabs;
mod packss;
mod packusdw;
mod packuswb;
mod padd;
mod padds;
mod paddus;
mod palignr;
mod pand;
mod pandn;
mod pause;
mod pavg;
mod pblendd;
mod pblendm;
mod pblendvb;
mod pblendvw;
mod pbroadcast;
mod pbroadcastmb2q;
mod pclmulqdq;
mod pcmp;
mod pcmpeq;
mod pcmpestri;
mod pcmpestrm;
mod pcmpgt;
mod pcmpistri;
mod pcmpistrm;
mod pcompress;
mod pconflict;
mod pdep;
mod pdpbusd;
mod pdpbusds;
mod pdpwssd;
mod pdpwssds;
mod perm;
mod perm2f128;
mod perm2i128;
mod permi2;
mod permilpd;
mod permilps;
mod permpd;
mod permps;
mod permq;
mod permt2;
mod pexpand;
mod pext;
mod pextr;
mod pgather;
mod phadd;
mod phaddsw;
mod phminposuw;
mod phsub;
mod phsubsw;
mod pinsr;
mod plzcnt;
mod pmadd52huq;
mod pmadd52luq;
mod pmaddubsw;
mod pmaddwd;
mod pmaskmov;
mod pmaxs;
mod pmaxu;
mod pmins;
mod pminu;
mod pmovdb;
mod pmovdw;
mod pmovm2;
mod pmovmskb;
mod pmovqb;
mod pmovqd;
mod pmovqw;
mod pmovsx;
mod pmovwb;
mod pmovx2m;
mod pmovzx;
mod pmuldq;
mod pmulhrsw;
mod pmulhuw;
mod pmulhw;
mod pmull;
mod pmulludq;
mod pmultishiftqb;
mod pop;
mod popa;
mod popcnt;
mod popf;
mod por;
mod prefetch;
mod prol;
mod pror;
mod psadbw;
mod pscatter;
mod pshld;
mod pshldv;
mod pshrd;
mod pshrdv;
mod pshufb;
mod pshufbitqmb;
mod pshufd;
mod pshufhw;
mod pshuflw;
mod pshufw;
mod psign;
mod psll;
mod pslldq;
mod psllv;
mod psra;
mod psrav;
mod psrl;
mod psrldq;
mod psrlv;
mod psub;
mod psubs;
mod psubus;
mod pternlog;
mod ptest;
mod ptestm;
mod ptestnm;
mod ptwrite;
mod punpckh;
mod punpckl;
mod push;
mod pusha;
mod pushf;
mod pxor;

pub use p2intersect::*;
pub use pabs::*;
pub use packss::*;
pub use packusdw::*;
pub use packuswb::*;
pub use padd::*;
pub use padds::*;
pub use paddus::*;
pub use palignr::*;
pub use pand::*;
pub use pandn::*;
pub use pause::*;
pub use pavg::*;
pub use pblendd::*;
pub use pblendm::*;
pub use pblendvb::*;
pub use pblendvw::*;
pub use pbroadcast::*;
pub use pbroadcastmb2q::*;
pub use pclmulqdq::*;
pub use pcmp::*;
pub use pcmpeq::*;
pub use pcmpestri::*;
pub use pcmpestrm::*;
pub use pcmpgt::*;
pub use pcmpistri::*;
pub use pcmpistrm::*;
pub use pcompress::*;
pub use pconflict::*;
pub use pdep::*;
pub use pdpbusd::*;
pub use pdpbusds::*;
pub use pdpwssd::*;
pub use pdpwssds::*;
pub use perm::*;
pub use perm2f128::*;
pub use perm2i128::*;
pub use permi2::*;
pub use permilpd::*;
pub use permilps::*;
pub use permpd::*;
pub use permps::*;
pub use permq::*;
pub use permt2::*;
pub use pexpand::*;
pub use pext::*;
pub use pextr::*;
pub use pgather::*;
pub use phadd::*;
pub use phaddsw::*;
pub use phminposuw::*;
pub use phsub::*;
pub use phsubsw::*;
pub use pinsr::*;
pub use plzcnt::*;
pub use pmadd52huq::*;
pub use pmadd52luq::*;
pub use pmaddubsw::*;
pub use pmaddwd::*;
pub use pmaskmov::*;
pub use pmaxs::*;
pub use pmaxu::*;
pub use pmins::*;
pub use pminu::*;
pub use pmovdb::*;
pub use pmovdw::*;
pub use pmovm2::*;
pub use pmovmskb::*;
pub use pmovqb::*;
pub use pmovqd::*;
pub use pmovqw::*;
pub use pmovsx::*;
pub use pmovwb::*;
pub use pmovx2m::*;
pub use pmovzx::*;
pub use pmuldq::*;
pub use pmulhrsw::*;
pub use pmulhuw::*;
pub use pmulhw::*;
pub use pmull::*;
pub use pmulludq::*;
pub use pmultishiftqb::*;
pub use pop::*;
pub use popa::*;
pub use popcnt::*;
pub use popf::*;
pub use por::*;
pub use prefetch::*;
pub use prol::*;
pub use pror::*;
pub use psadbw::*;
pub use pscatter::*;
pub use pshld::*;
pub use pshldv::*;
pub use pshrd::*;
pub use pshrdv::*;
pub use pshufb::*;
pub use pshufbitqmb::*;
pub use pshufd::*;
pub use pshufhw::*;
pub use pshuflw::*;
pub use pshufw::*;
pub use psign::*;
pub use psll::*;
pub use pslldq::*;
pub use psllv::*;
pub use psra::*;
pub use psrav::*;
pub use psrl::*;
pub use psrldq::*;
pub use psrlv::*;
pub use psub::*;
pub use psubs::*;
pub use psubus::*;
pub use pternlog::*;
pub use ptest::*;
pub use ptestm::*;
pub use ptestnm::*;
pub use ptwrite::*;
pub use punpckh::*;
pub use punpckl::*;
pub use push::*;
pub use pusha::*;
pub use pushf::*;
pub use pxor::*;
